app/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("admin/", admin.site.urls), path("", include("inventory.urls"))]

app/inventory/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    # Edit Single Entry
    path(
        "deploy/<int:pk>/edit/", views.DeviceUpdateView.as_view(), name="device_update"
    ),
    # Search Result
    path(
        "search/deployed/result/",
        views.DeviceSearchView.as_view(),
        name="device_search_result",
    ),
    path(
        "search/return/result/",
        views.ReturnDeviceSearchView.as_view(),
        name="return_search_result",
    ),
    path("search/deployed/", views.DeployedSearchView.as_view(), name="deploy_search"),
    path("search/return/", views.ReturnSearchView.as_view(), name="return_search"),
    path("inventory/", views.DeviceListView.as_view(), name="inventory_main"),
    path("deploy/", views.DeviceCreateView.as_view(), name="device_deploy"),
    path(
        "deploy-bulk/", views.BulkDeviceCreateView.as_view(), name="device_deploy_bulk"
    ),
    path("deploy/<int:pk>/", views.DeployedDetailView.as_view(), name="device_detail"),
    path("", views.HomePageView.as_view(), name="home"),
    # ajax url
    path("ajax/load-models/", views.load_models, name="ajax_load_models"),
    path(
        "ajax/check_unique_serial_number/",
        views.check_unique_serial_number,
        name="ajax_check_unique_serial_number",
    ),
]

app/inventory/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class DeviceType(models.Model):
    name = models.CharField(max_length=30, null=False)

    def __str__(self):
        return self.name


class DeviceModel(models.Model):
    name = models.CharField(max_length=30, null=False)
    deviceType = models.ForeignKey(
        DeviceType, on_delete=models.CASCADE, null=False, default="testing"
    )

    def __str__(self):
        return self.name


class Device(models.Model):
    deviceType = models.ForeignKey(DeviceType, on_delete=models.CASCADE, null=False)
    deviceModel = models.ForeignKey(DeviceModel, on_delete=models.CASCADE, null=False)
    site_choices = [
        ("F10N", "F10N"),
        ("F10W", "F10W"),
        ("F10A", "F10A"),
        ("F10X", "F10X"),
        ("MSB", "MSB"),
    ]
    site = models.CharField(max_length=5, choices=site_choices, null=True)
    ownership_choices = [
        ("Primary Device", "Primary Device"),
        ("Secondary Device", "Secondary Device"),
        ("Share Device", "Share Device"),
        ("VIP Device", "VIP Device"),
    ]
    ownership = models.CharField(
        max_length=20, choices=ownership_choices, default="Primary Device"
    )

    serialnumber = models.CharField(max_length=15, unique=True, null=False)
    deviceOwner = models.CharField(max_length=10, null=False)
    submittor = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    remarks = models.TextField(max_length=200, blank=True)

    def __str__(self):
        return f"{self.deviceModel} - {self.serialnumber} deployed to {self.deviceOwner} on {self.created_at}"

    def save(self, *args, **kwargs):
        for field_name in ["serialnumber", "deviceOwner"]:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.upper())  # Change attr to upper

        return super(Device, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("device_detail", args=[str(self.id)])

app/inventory/views.py
from django.db.models import Q
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)
from django.views.generic.base import ContextMixin

from .form import DeviceForm
from .models import Device, DeviceModel

# Render View


def load_models(request):
    deviceType_id = request.GET.get("type")
    models = DeviceModel.objects.filter(deviceType_id=deviceType_id).order_by("name")
    return render(request, "model_dropdown_list_options.html", {"models": models})


def check_unique_serial_number(request):
    serial_number = request.GET.get("serialnumber")
    # print(serial_number)
    exist = Device.objects.filter(serialnumber=serial_number).exists()
    if not exist:
        return HttpResponse(f"{serial_number} is unique")
    else:
        return HttpResponseBadRequest()


# Create your views here.


class HomePageView(TemplateView):
    template_name = "index.html"


class DeployedSearchView(TemplateView):
    template_name = "deployed_search.html"


class ReturnSearchView(TemplateView):
    template_name = "return_search.html"


class DeviceListView(ListView):
    model = Device
    template_name = "inventory.html"


class DeviceCreateView(CreateView):
    model = Device
    form_class = DeviceForm
    template_name = "deploy_single.html"


class BulkDeviceCreateView(DeviceCreateView):
    template_name = "deploy_bulk.html"


class DeployedDetailView(DetailView):
    model = Device
    template_name = "device_detail.html"


class DeviceUpdateView(UpdateView):
    model = Device
    template_name = "device_update.html"
    fields = "__all__"


class DeviceSearchView(ListView):
    model = Device
    template_name = "device_search_result.html"

    def get_queryset(self):  # new
        serialnum = self.request.GET.get("serialnum")
        userid = self.request.GET.get("userid")
        if serialnum:
            object_list = Device.objects.filter(Q(serialnumber__icontains=serialnum))

        if userid:
            object_list = Device.objects.filter(Q(deviceOwner__icontains=userid))
            # print(len(object_list))
        return object_list


class ReturnDeviceSearchView(DeviceSearchView):
    model = Device
    template_name = "return_search_result.html"

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            device_ids = request.POST.get("ids", "")
            device_ids = device_ids.split(",")
            print(device_ids)
            self.model.objects.filter(id__in=device_ids).delete()
            return JsonResponse({"status": "ok"}, status=204)

app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
      integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"
    />
    <link
      href="{% static 'css/style.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <title>Asset Management App Demo</title>
  </head>
  <body>
    <div class="text-dark py-3">
      <a href="{% url 'home' %}"
        ><h1 class="text-center">Asset Management App Demo</h1></a
      >
      <hr />
    </div>
    {% block content %} {% endblock content %}
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"
      integrity="sha512-n/4gHW3atM3QqRcbCn6ewmpxcLAHGaDjpEBu4xZd47N0W2oQ+6q7oc3PXstrJYXcbNU1OHdQ1T7pAP+gi5Yu8g=="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
      integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"
      integrity="sha512-RXf+QSDCUQs5uwRKaDoXt55jygZZm2V++WUZduaU/Ui/9EGp3f/2KZVahFZBKGH0s774sd3HmrhUy+SgOFQLVQ=="
      crossorigin="anonymous"
    ></script>

    {% block script %} {% endblock script %}
  </body>
</html>

app/templates/deploy.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10  mx-auto">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title text-center">New Deployment</h4>
                    <hr>
                    <form method="post" id="deploymentForm" data-models-url = "{% url 'ajax_load_models' %}" >
                        {% csrf_token %}
                        <div class="row">
                            <div class="form-group col-md-5 mb-0">
                                {{ form.deviceType|as_crispy_field}}
                            </div>
                            <div class="form-group col-md-5 mb-0">
                                {{ form.deviceModel|as_crispy_field}}
                            </div>
                            <div class="form-group col-md-2 mb-0">
                                {{ form.site|as_crispy_field}}
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-3 mb-0">
                                {{ form.serialnumber|as_crispy_field}}
                            </div>
                            <div class="form-group col-md-3 mb-0">
                                {{ form.deviceOwner|as_crispy_field}}
                            </div>
                            <div class="form-group col-md-3 mb-0">
                                {{ form.ownership|as_crispy_field}}
                            </div>
                            <div class="form-group col-md-3 mb-0">
                                {{ form.submittor|as_crispy_field}}
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md mb-0">
                                {{ form.remarks|as_crispy_field}}
                            </div>
                        </div>
                        <input type="submit" class="btn btn-block btn-success" value='Save'>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

{% block script %}
<script>
    document.getElementById("id_remarks").rows = "5";

    $("#id_deviceType").change(function () {
        var url = $("#deploymentForm").attr("data-models-url");  // get the url of the `ajax_load_models` view
        var devicetypeId = $(this).val();  // get the selected deviceType ID from the HTML input

        if(devicetypeId == ''){
            $("#id_deviceModel").html('<option value="">---------</option>')
        } else {

            $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                'type': devicetypeId       // add the deviceType id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_deviceModel").html(data);  // replace the contents of the model input with the data that came from the server
            }
            });
        }
  
      });


</script>
{% endblock script %}

app/templates/deploy_bulk.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col mx-auto">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <div class="card mb-3">
                <div class="card-body">
                  <h4 class="card-title text-center" class="mb-0">User Info</h4>
                  <hr />
                  <div class="row">
                    <div class="col-sm-6">
                      <label for="username">Micron Username*</label>
                      <input
                        type="text"
                        id="username"
                        class="form-control mb-3"
                        placeholder="Username"
                      />
                    </div>
                    <div class="col-sm-6">{{ form.site|as_crispy_field}}</div>
                  </div>
                  <div class="form-group">
                    {{ form.remarks|as_crispy_field}}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div
                class="card"
                data-models-url="{% url 'ajax_load_models' %}"
                id="card_input"
              >
                <div class="card-body">
                  <h4 class="card-title text-center">Devices to deploy</h4>
                  <table class="table mb-0" id="deployed_table">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Device type</th>
                        <th>Device model</th>
                        <th>Serial number</th>
                        <th>Ownership type</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row">
                          <a href="#" id="add_more"
                            ><i class="fas fa-plus text-info"></i
                          ></a>
                        </th>
                        <td>{{ form.deviceType|as_crispy_field}}</td>
                        <td>{{ form.deviceModel|as_crispy_field}}</td>
                        <td
                          id="sn_field"
                          data-models-url="{% url 'ajax_check_unique_serial_number' %}"
                        >
                          {{ form.serialnumber|as_crispy_field}}
                        </td>
                        <td>{{ form.ownership|as_crispy_field}}</td>
                      </tr>
                    </tbody>
                  </table>
                  <!-- <button id="add_more" class="btn btn-block btn-primary btn-sm text-center mt-0 mb-2"><i class="fas fa-plus fa-1x"></i> Add another device</button> -->
                  <button
                    id="deploy_bulk_save"
                    type="submit"
                    class="btn btn-block btn-primary btn-sm text-center mt-0 mb-2"
                    disabled
                  >
                    <i class="fas fa-plus fa-1x"></i> Save
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %} {% block script %}
<script>
  document.getElementById("id_remarks").rows = "2";
  $("#id_deviceType").change(function () {
    var url = $("#card_input").attr("data-models-url"); // get the url of the `ajax_load_models` view
    var devicetypeId = $(this).val(); // get the selected deviceType ID from the HTML input

    if (devicetypeId == "") {
      $("#id_deviceModel").html('<option value="">---------</option>');
    } else {
      $.ajax({
        // initialize an AJAX request
        url: url,
        data: {
          type: devicetypeId, // add the deviceType id to the GET parameters
        },
        success: function (data) {
          // `data` is the return of the `load_cities` view function
          $("#id_deviceModel").html(data); // replace the contents of the model input with the data that came from the server
        },
      });
    }
  });
  $(".form-control").addClass("form-control-sm");
  $("#deployed_table label").remove();

  document.getElementById("add_more").addEventListener("click", function () {
    var deviceType = $("#id_deviceType").val();
    var deviceModel = $("#id_deviceModel").val();
    var serialnumber = $("#id_serialnumber").val().toUpperCase();
    var ownership = $("#id_ownership").val();

    if (deviceType && deviceModel && serialnumber) {
      var url = $("#sn_field").attr("data-models-url");
      $.ajax({
        url: url,
        data: {
          serialnumber: serialnumber,
        },
        success: function (data) {
          var table = document.getElementById("deployed_table");
          var rowCount = table.rows.length;
          var row = table.insertRow(rowCount - 1);

          var colCount = table.rows[0].cells.length;
          var cell0 = row.insertCell(0);
          cell0.innerHTML =
            '<a class="text-center text-danger delete-button" href="#"><i class="fas fa-times"></i></a>';
          var cell1 = row.insertCell(1);
          cell1.innerText = $("#id_deviceType option:selected").text();
          var cell2 = row.insertCell(2);
          cell2.innerText = $("#id_deviceModel option:selected").text();
          var cell3 = row.insertCell(3);
          cell3.innerText = serialnumber.toUpperCase();
          var cell4 = row.insertCell(4);
          cell4.innerText = ownership;
          console.log(
            "added",
            deviceType,
            deviceModel,
            serialnumber,
            ownership
          );
          $("#id_deviceType").val("");
          $("#id_deviceModel").val("");
          $("#id_serialnumber").val("");
          $("#id_ownership").val("Primary Device");
          console.log(data);
        },
        error: function () {
          alert(serialnumber + " exists in the database");
        },
      });
    } else {
      alert("Please fill something");
    }
  });

  $("#deployed_table").on("click", ".delete-button", function (e) {
    $(this).closest("tr").remove();
  });

  document.querySelector("body").addEventListener("click", function () {
    var table = document.getElementById("deployed_table");
    var rowCount = table.rows.length;

    if (rowCount > 2) {
      document.getElementById("deploy_bulk_save").disabled = false;
    } else {
      document.getElementById("deploy_bulk_save").disabled = true;
    }
  });
</script>
{% endblock script %}

app/templates/deploy_single.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col mx-auto">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title text-center">New Deployment</h4>
          <hr />
          <form
            method="post"
            id="deploymentForm"
            data-models-url="{% url 'ajax_load_models' %}"
          >
            {% csrf_token %}
            <div class="row">
              <div class="form-group col-md-5 mb-0">
                {{ form.deviceType|as_crispy_field}}
              </div>
              <div class="form-group col-md-5 mb-0">
                {{ form.deviceModel|as_crispy_field}}
              </div>
              <div class="form-group col-md-2 mb-0">
                {{ form.site|as_crispy_field}}
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-3 mb-0">
                {{ form.serialnumber|as_crispy_field}}
              </div>
              <div class="form-group col-md-3 mb-0">
                {{ form.deviceOwner|as_crispy_field}}
              </div>
              <div class="form-group col-md-3 mb-0">
                {{ form.ownership|as_crispy_field}}
              </div>
              <div class="form-group col-md-3 mb-0">
                {{ form.submittor|as_crispy_field}}
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md mb-0">
                {{ form.remarks|as_crispy_field}}
              </div>
            </div>
            <input
              type="submit"
              class="btn btn-block btn-success"
              value="Save"
            />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %} {% block script %}
<script>
  document.getElementById("id_remarks").rows = "5";

  $("#id_deviceType").change(function () {
    var url = $("#deploymentForm").attr("data-models-url"); // get the url of the `ajax_load_models` view
    var devicetypeId = $(this).val(); // get the selected deviceType ID from the HTML input

    if (devicetypeId == "") {
      $("#id_deviceModel").html('<option value="">---------</option>');
    } else {
      $.ajax({
        // initialize an AJAX request
        url: url,
        data: {
          type: devicetypeId, // add the deviceType id to the GET parameters
        },
        success: function (data) {
          // `data` is the return of the `load_cities` view function
          $("#id_deviceModel").html(data); // replace the contents of the model input with the data that came from the server
        },
      });
    }
  });
</script>
{% endblock script %}

app/templates/deployed_search.html
{% extends "search_template.html" %} {% block subtitle %} Search Deployed Device
{% endblock subtitle %} {% block script %}
<script>
  var form = document.getElementById("searchform");
  form.action = "{% url 'device_search_result' %}";
</script>
{% endblock script %}

app/templates/device_detail.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <p class="card-text mb-1 small font-weight-bold">Device Deployed</p>
          <h3 class="card-title">{{ device.deviceModel }}</h3>
          <p class="card-text">
            This device is deployed to <span>{{device.deviceOwner}}</span> on
            {{device.created_at|date:"SHORT_DATETIME_FORMAT" }}
          </p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Type: {{device.deviceType}}</li>
          <li class="list-group-item">S/N: {{device.serialnumber}}</li>
          <li class="list-group-item">Site: {{device.site}}</li>
          {% if device.remarks != '' %}
          <li class="list-group-item">Remarks: {{device.remarks}}</li>
          {% endif %}
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div class="row mb-3">
        <a
          href="{% url 'device_deploy' %}"
          class="btn btn-primary btn-block btn-lg"
          >Deploy A Device</a
        >
      </div>
      <div class="row mb-3">
        <a
          href="{% url 'device_update' device.pk %}"
          class="btn btn-warning btn-block btn-lg text-white"
          >Edit Entry</a
        >
      </div>
      <div class="row">
        <a
          href="{% url 'inventory_main' %}"
          class="btn btn-success btn-block btn-lg"
          >View Inventory</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock content %}

app/templates/device_search_result.html
{% extends 'inventory.html' %} {% block th %}
<th></th>
{% endblock th %} {% block td %}
<td><a href="{% url 'device_update' device.pk %}" class="">Edit</a></td>
{% endblock td %}

app/templates/device_update.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="row">
  <div class="col-md-10 mx-auto">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title text-center">Edit Record</h4>
        <hr />
        <form method="post">
          {% csrf_token %}
          <div class="row">
            <div class="form-group col-md-5 mb-0">
              {{ form.deviceType|as_crispy_field}}
            </div>
            <div class="form-group col-md-5 mb-0">
              {{ form.deviceModel|as_crispy_field}}
            </div>
            <div class="form-group col-md-2 mb-0">
              {{ form.site|as_crispy_field}}
            </div>
          </div>
          <div class="row">
            <div class="form-group col-md-3 mb-0">
              {{ form.serialnumber|as_crispy_field}}
            </div>
            <div class="form-group col-md-3 mb-0">
              {{ form.deviceOwner|as_crispy_field}}
            </div>
            <div class="form-group col-md-3 mb-0">
              {{ form.ownership|as_crispy_field}}
            </div>
            <div class="form-group col-md-3 mb-0">
              {{ form.submittor|as_crispy_field}}
            </div>
          </div>
          <div class="row">
            <div class="form-group col-md mb-0">
              {{ form.remarks|as_crispy_field}}
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <input
                type="submit"
                class="btn btn-block btn-success"
                value="Save"
              />
            </div>
            <div class="col-md-6">
              <a
                href="{% url 'device_detail' device.pk %}"
                class="btn btn-danger btn-block"
                >Cancel</a
              >
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script>
  document.getElementById("id_remarks").rows = "5";
</script>
{% endblock content %}

app/templates/index.html
{% extends 'base.html' %} {% block content %}
<section id="main">
  <div class="container text-center">
    <div class="row">
      <div class="col">
        <div class="card mx-auto">
          <div class="card-body">
            <h4 class="card-title">Select One Below</h4>
            <hr />
            <div id="selector-main">
              <div class="row">
                <div class="col-sm-4">
                  <div class="card">
                    <div class="card-body">
                      <p class="card-text">Device Deployment</p>
                      <div class="row">
                        <div class="col">
                          <button
                            id="deployment_select"
                            class="btn btn-outline-success btn-block"
                          >
                            Deploy
                          </button>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-6">
                          <a
                            href="{% url 'device_deploy' %}"
                            class="btn btn-outline-success btn-block deploy_choice"
                            hidden
                            >Deploy Single</a
                          >
                        </div>
                        <div class="col-md-6">
                          <a
                            href="{% url 'device_deploy_bulk' %}"
                            class="btn btn-outline-success btn-block deploy_choice"
                            hidden
                            >Deploy Bulk</a
                          >
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-sm-4">
                  <div class="card">
                    <div class="card-body">
                      <p class="card-text">Edit an asset record</p>
                      <a
                        href="{% url 'deploy_search' %}"
                        id="edit"
                        class="btn btn-outline-warning btn-block"
                        >Edit</a
                      >
                    </div>
                  </div>
                </div>
                <div class="col-sm-4">
                  <div class="card">
                    <div class="card-body">
                      <p class="card-text">Return a device</p>
                      <a
                        href="{% url 'return_search' %}"
                        id="return"
                        class="btn btn-outline-danger btn-block"
                        >Return</a
                      >
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col">
                <a
                  href="{% url 'inventory_main' %}"
                  class="btn btn-success btn-block btn-lg"
                  >View Inventory</a
                >
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %} {% block script %}
<script>
  var deploybtn = document.getElementById("deployment_select");
  deploybtn.addEventListener("click", function (e) {
    deploybtn.hidden = true;
    document.querySelectorAll(".deploy_choice").forEach(function (button) {
      console.log(button);
      button.removeAttribute("hidden");
    });
    e.preventDefault();
  });
</script>
{% endblock script %}

app/templates/inventory.html
{% extends 'base.html' %} {% block content %}

<div class="row my-3">
  <div class="col-md-10 mx-auto">
    <div class="card mx-auto">
      <div class="card-body">
        <h3 class="card-title text-center">
          {% block tabletitle %} Inventory List {% endblock tabletitle %}
        </h3>
        <hr />
        <div class="row">
          <div class="col">
            <table class="table table-hover table-sm">
              <thead class="thead-light">
                <tr id="{{ device.pk }}">
                  <th scope="col">#</th>
                  <th scope="col">Device Type</th>
                  <th scope="col">Device Model</th>
                  <th scope="col">S/N</th>
                  <th scope="col">Device Owner</th>
                  <th scope="col">Site</th>
                  <th scope="col">Device Ownership</th>
                  <th scope="col">Remarks</th>
                  <th scope="col">Added On</th>
                  <th scope="col">Last Modified On</th>
                  <th scope="col">Modified By</th>
                  {% block th %} {% endblock th %}
                </tr>
              </thead>
              <tbody>
                {% csrf_token %} {% for device in object_list %}
                <tr>
                  <th scope="row">{{ device.pk }}</th>
                  <td>{{device.deviceType}}</td>
                  <td>{{device.deviceModel}}</td>
                  <td>{{device.serialnumber}}</td>
                  <td>{{device.deviceOwner}}</td>
                  <td>{{device.site}}</td>
                  <td>{{device.ownership}}</td>
                  <td>{{device.remarks|truncatewords:"20"}}</td>
                  <td>{{device.created_at|date:"SHORT_DATETIME_FORMAT" }}</td>
                  <td>{{device.updated_at|date:"SHORT_DATETIME_FORMAT"}}</td>
                  <td>{{device.submittor}}</td>
                  {% block td %} {% endblock td %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% block aftertable %} {% endblock aftertable %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %} {% block script %}
<script>
  $(document).ready(function () {
    $('[data-toggle="tooltip"]').tooltip();
  });
</script>
{% endblock script %}

app/templates/model_dropdown_list_options.html
<option value="">---------</option>
{% for model in models %}
<option value="{{ model.pk }}">{{ model.name }}</option>
{% endfor %}